language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.2.2
  - 2.2.3
  - 2.3.0

gemfile: Gemfile

# Test for various gem versions we currently support
matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/old-rubies.gemfile
      script:
        - bundle exec rake test
        - bundle exec rspec test
    - rvm: 1.8.7
      gemfile: gemfiles/rspec.2.99.gemfile
      script: bundle exec rspec test
    - rvm: 1.9.3
      gemfile: gemfiles/old-rubies.gemfile
      script:
        - bundle exec rake test
        - bundle exec rspec test
    - rvm: 1.9.3
      gemfile: gemfiles/rspec.2.99.gemfile
      script: bundle exec rspec test
    - rvm: 2.2.2
      gemfile: gemfiles/rspec.2.99.gemfile
      script: bundle exec rspec test
    - rvm: 2.2.2
      gemfile: gemfiles/minitest.4.7.5.gemfile
      script: bundle exec rake test
    - rvm: 2.2.2
      gemfile: gemfiles/minitest.gemfile
      script: bundle exec rake test
    - rvm: 2.2.2
      gemfile: gemfiles/test-unit.gemfile
      script: bundle exec rake test
    - rvm: 2.2.2
      gemfile: gemfiles/rspec.gemfile
      script: bundle exec rake spec
    - rvm: 2.2.3
      gemfile: gemfiles/rspec.2.99.gemfile
      script: bundle exec rspec test
    - rvm: 2.2.3
      gemfile: gemfiles/minitest.4.7.5.gemfile
      script: bundle exec rake test
    - rvm: 2.2.3
      gemfile: gemfiles/minitest.gemfile
      script: bundle exec rake test
    - rvm: 2.2.3
      gemfile: gemfiles/test-unit.gemfile
      script: bundle exec rake test
    - rvm: 2.2.3
      gemfile: gemfiles/rspec.gemfile
      script: bundle exec rake spec
    - rvm: 2.3.0
      gemfile: gemfiles/rspec.2.99.gemfile
      script: bundle exec rspec test
    - rvm: 2.3.0
      gemfile: gemfiles/minitest.4.7.5.gemfile
      script: bundle exec rake test
    - rvm: 2.3.0
      gemfile: gemfiles/minitest.gemfile
      script: bundle exec rake test
    - rvm: 2.3.0
      gemfile: gemfiles/test-unit.gemfile
      script: bundle exec rake test
    - rvm: 2.3.0
      gemfile: gemfiles/rspec.gemfile
      script: bundle exec rake spec
